export const bugServiceData = [
  {
    id: 101,
    title: "Haşere İlaçlama",
    description: "Ev ve iş yerlerinizde haşere kontrolü",
    detailedDescription:
      "Ev ve iş yerlerinde karınca, hamamböceği, pire ve diğer haşerelerden etkili koruma sağlıyoruz. Uzman ekibimiz çevre dostu ürünler ile güvenli uygulama yapar.",
    image: "https://turacevre.com/images/upload/thumb/_1743162650.jpg",
    features: [
      "Hızlı ve etkili çözüm",
      "Güvenli ürünler",
      "Acil müdahale",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 102,
    title: "Böcek İlaçlama",
    description: "Profesyonel böcek kontrol hizmeti",
    detailedDescription:
      "Ev, ofis ve depolarda böceklerden tamamen kurtulmanız için etkili ilaçlama hizmeti sunuyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743161705.jpg",
    features: [
      "Hızlı ve güvenli",
      "Etkin çözüm",
      "Uzman ekip",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 103,
    title: "Hamam Böceği İlaçlama",
    description: "Hamam böceklerinden hızlı çözüm",
    detailedDescription:
      "Ev ve iş yerlerinde hamam böceklerinden tamamen kurtulmanız için uzman ekibimiz ile güvenli uygulama yapıyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743163433.jpg",
    features: [
      "Hızlı müdahale",
      "Güvenli ve etkili",
      "Periyodik kontrol",
      "Acil çözüm",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 104,
    title: "Fare İlaçlama",
    description: "Ev ve depo fare kontrol hizmeti",
    detailedDescription:
      "Farelerden kurtulmak için etkili ve güvenli ilaçlama hizmeti sunuyoruz. Profesyonel ekibimiz ile hijyenik çözümler sağlıyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743163990.jpg",
    features: [
      "Etkin çözüm",
      "Hijyenik uygulama",
      "Uzman ekip",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 105,
    title: "Kene İlaçlama",
    description: "Bahçe ve çevre kene kontrolü",
    detailedDescription:
      "Bahçe ve çevre alanlarında kenelere karşı etkili ve güvenli koruma sağlıyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743166899.jpg",
    features: [
      "Hızlı ve güvenli",
      "Etkin kontrol",
      "Uzman uygulama",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 106,
    title: "Pire İlaçlama",
    description: "Evcil hayvan ve ev ortamında pire kontrolü",
    detailedDescription:
      "Evcil hayvanlar ve ev ortamında pirelerden kurtulmak için güvenli ve etkili ilaçlama çözümleri sunuyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743164445.jpg",
    features: [
      "Güvenli uygulama",
      "Hızlı müdahale",
      "Periyodik kontrol",
      "Etkin çözüm",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 107,
    title: "Tahta Kurusu İlaçlama",
    description: "Yatak ve mobilya zararlıları kontrolü",
    detailedDescription:
      "Yatak ve mobilyalardaki tahta kurularına karşı etkili ilaçlama hizmeti sunuyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743167289.jpg",
    features: [
      "Güvenli uygulama",
      "Hijyenik çözüm",
      "Uzman ekip",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
  {
    id: 108,
    title: "Karınca İlaçlama",
    description: "Ev ve iş yerlerinizde karınca kontrolü",
    detailedDescription:
      "Ev ve iş yerlerinde karıncalardan kurtulmak için güvenli ve etkili ilaçlama hizmeti sunuyoruz.",
    image: "https://turacevre.com/images/upload/thumb/_1743168389.jpg",
    features: [
      "Hızlı ve güvenli",
      "Etkin çözüm",
      "Hijyenik uygulama",
      "Periyodik kontrol",
    ],
    price: "Fiyat teklifi için iletişime geçin",
    duration: "Hızlı Çözüm",
    warranty: "Memnuniyet garantisi",
  },
];
